export const SettingsState = {
  mail_title_template: '',
  mail_body_template: '',
  id: null,
  corporate_division: null,
  tax_consumption: 1,
  tax_rate: '',
  tax_rounding: 1,
  tax_withholding: 1,
};

export const InfoSettingState = {
  name: '',
  closing_month: '',
  qualified_invoice_issuer_code: '',
  department_name: '',
  representative_name: '',
  postal_code: '',
  address_street_1: '',
  address_street_2: '',
  email: '',
  tel: '',
  mail_title_template: '',
  mail_body_template: '',
  id: null,
  corporate_division: 1,
  tax_consumption: 1,
  tax_rate: '',
  tax_rounding: 1,
  tax_withholding: 1,
};
